apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstoreapp
spec: 
  selector:
    matchLabels:
      app: petstoreapp
  replicas: 1
  template:
    metadata:
      labels:
        app: petstoreapp
    spec:
      containers:
        - name: petstoreapp
          image: nswamy9/petstoreapp:V1
          env:
            - name: DATABASE_URL
              value: postgresql://Timi:my_fake_password@postgres-service:5432/Timi_db
          ports: 
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: pet-store-service
spec:
  type: LoadBalancer
  selector:
     app: petstoreapp
  ports:
    - name: http
      port: 80
      targetPort: 8080