apiVersion : apps/v1
kind: Deployment
metadata:
  name: postgres
spec: 
  selector: 
    matchLabels:
      app: postgres
  replicas: 1
  template: 
    metadata: 
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: prostgres
          env:
            - name: POSTGRES_USER
              value: Timi 
            - name: POSTGRES_PASSWORD
              value: my_fake_password
            - name: POSTGRES_DB
              value: Timi_db
          ports: 
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec: 
  selector: 
    app: postgres
  ports: 
    - name: postgres
      port: 5432
      targetPort: 5432
        